export const CONTINENTS_FEAT = 'CONTINENTS';

export const LOAD_CONTINENTS = `${CONTINENTS_FEAT}_LOAD`;
export const LOAD_CONTINENTS_SUCCESS = `${CONTINENTS_FEAT}_LOAD_SUCCESS`;
export const LOAD_CONTINENTS_FAIL = `${CONTINENTS_FEAT}_LOAD_FAIL`;

export const STATS_FEAT = 'STATS';

export const LOAD_STATS = `${STATS_FEAT}_LOAD`;
export const LOAD_STATS_SUCCESS = `${STATS_FEAT}_LOAD_SUCCESS`;
export const LOAD_STATS_FAIL = `${STATS_FEAT}_LOAD_FAIL`;

export const AUTH_FEAT = 'AUTH';

export const AUTH_LOGIN = `${AUTH_FEAT}_LOGIN`;
export const AUTH_LOGIN_SUCCESS = `${AUTH_FEAT}_LOGIN_SUCCESS`;
export const AUTH_LOGIN_FAIL = `${AUTH_FEAT}_LOGIN_FAIL`;

export const AUTH_SIGNUP = `${AUTH_FEAT}_SIGNUP`;
export const AUTH_SIGNUP_SUCCESS = `${AUTH_FEAT}_SIGNUP_SUCCESS`;
export const AUTH_SIGNUP_FAIL = `${AUTH_FEAT}_SIGNUP_FAIL`;

export const AUTH_REFRESH_TOKEN = `${AUTH_FEAT}_REFRESH_TOKEN`;
export const AUTH_REFRESH_TOKEN_SUCCESS = `${AUTH_FEAT}_REFRESH_TOKEN_SUCCESS`;
export const AUTH_REFRESH_TOKEN_FAIL = `${AUTH_FEAT}_REFRESH_TOKEN_FAIL`;

export const AUTH_LOGOUT = `${AUTH_FEAT}_LOGOUT`;
export const AUTH_LOGOUT_SUCCESS = `${AUTH_FEAT}_LOGOUT_SUCCESS`;
export const AUTH_LOGOUT_FAIL = `${AUTH_FEAT}_LOGOUT_FAIL`;

export const AUTH_VERIFY_LOGIN = `${AUTH_FEAT}_VERIFY_LOGIN`;
export const AUTH_VERIFY_LOGIN_SUCCESS = `${AUTH_FEAT}_VERIFY_LOGIN_SUCCESS`;
