export const CONTINENTS_FEAT = 'CONTINENTS';

export const LOAD_CONTINENTS = `${CONTINENTS_FEAT}_LOAD`;
export const LOAD_CONTINENTS_SUCCESS = `${CONTINENTS_FEAT}_LOAD_SUCCESS`;
export const LOAD_CONTINENTS_FAIL = `${CONTINENTS_FEAT}_LOAD_FAIL`;

export const STATS_FEAT = 'STATS';

export const LOAD_STATS = `${STATS_FEAT}_LOAD`;
export const LOAD_STATS_SUCCESS = `${STATS_FEAT}_LOAD_SUCCESS`;
export const LOAD_STATS_FAIL = `${STATS_FEAT}_LOAD_FAIL`;
